# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e60f9161279eaf8d3d55b0128b93f489fa6b80f35b5efaace0cdae6a28e712ccdbc7cd14cbcc0ee8e36f7e30f3c5ba7c247b739e1eeafbf5ed5aa156d14fe024

test:
  secret_key_base: 61007e49e5d450888283830aac6b8b0c70b4d9fd212be9c6f197e25baf0d8f48385b94f7e627efdc1f12da46bedf08633145321495235c79da4867a41def8d07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
